//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restoran
{
    using System;
    using System.Collections.Generic;
    
    public partial class Musteri
    {
        public int MusteriID { get; set; }
        public string musteriName { get; set; }
        public string musteriPhone { get; set; }
        public string musteriBudget { get; set; }
        public string musteriAdress { get; set; }
        public int RestoranID { get; set; }
    }
}
