//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restoran
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restoran
    {
        public int RestoranID { get; set; }
        public string restoranName { get; set; }
        public string restoranAdress { get; set; }
        public decimal restoranSalary { get; set; }
        public string restoranPhone { get; set; }
    }
}
