//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restoran
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siparis
    {
        public int SiparisID { get; set; }
        public string siparisPrice { get; set; }
        public int RestoranID { get; set; }
        public int MusteriID { get; set; }
        public int urunCount { get; set; }
        public string urunSecim { get; set; }
    }
}
