//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restoran
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urun
    {
        public int UrunID { get; set; }
        public string urunName { get; set; }
        public decimal urunPrice { get; set; }
        public string urunType { get; set; }
        public int RestoranID { get; set; }
    }
}
